### ISSUE TITLE
When can I get getAccessToken changes in gradle version? Curently it is 0.9.0 which doesnt have these changes.

### ISSUE THREAD

**Issue by karnshah8890** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#13]
@peternied Would you please help me in this? I am working on application. So need [these](https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter/commit/913c8d6844ccb55584fd376237fcf60512206353) changes as soon as possible.

**Comment by cbales** [comment]
Thanks for your patience. The gradle package has now been updated to include these changes.
