### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by matthewcarlreetz** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#15]
The app I'm creating requires the ability to simultaneously support multiple Outlook accounts. I'm not seeing a way to do that with the sdk. Is it possible?

**Comment by fiasko131** [comment]
is there an advancement on this topic? All other cloud providers can manage multiple accounts easily ...

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
