### ISSUE TITLE
fixed version number for dependencies

### ISSUE THREAD

**Issue by kassim** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#16]
this
```
dependencies {
    compile 'com.microsoft.services.msa:msa-auth:+'
    compile 'com.microsoft.graph:msgraph-sdk-android:+'
}
```
https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter/blob/master/lib/build.gradle

is bad practice

it causes builds to potentially fail when a new release comes out

could you keep it to a fixed version number please

**Comment by cbales** [comment]
I agree that typically it is bad practice to have open-ended dependency versions. However, since this adapter is so tightly coupled to the SDK and MSAL, if these dependencies fail, the adapter needs to be fixed.
