### ISSUE TITLE
The app is not responding, when click "Back" button in "Sign in" UI. 

### ISSUE THREAD

**Issue by gavinzheng18** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#17]
The APP called the authenticationAdapter.login(getActivity(), new ICallback<Void>() {...}) function to show login UI. The app is not responding, when click "Back" button in "Sign in" UI. Then, popup dialog to show " XXX isn't responding. Do you want to close it?", the "XXX" is application name.
The following operations cause the same issue:
1.Click "Back" button in "Create account" UI;
2.Click "<-" button in "Enter password" UI;

**Comment by hodangquocdat** [comment]
I have a similar situation.

**Comment by Kevinmrqz** [comment]
Same problem.

**Comment by AlexeyMatrosov** [comment]
Same problem still =(

**Comment by priyankagb** [comment]
same issue. Is there any solution for it?

**Comment by keeblebogdan** [comment]
Any solution?

**Comment by apetroaeiandrei** [comment]
Microsoft doesn't care!

**Comment by baywet** [comment]
Hi everyone,
Thank you for the contribution, we have moved away from an android specific SDK to a [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java) and this repo will be archived very soon.
If you're still facing the same issue with the Java SDK, feel free to re-open an issue over there.
Closing.
