### ISSUE TITLE
Any reason why hasValidSession() is private in MSAAuthAndroidAdapter()?

### ISSUE THREAD

**Issue by morphine9** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#4]
[hasValidSession()](https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter/blob/master/lib/src/main/java/com/microsoft/graph/authentication/MSAAuthAndroidAdapter.java#L300) might as well be public since developers can check for session before calling for login?

**Comment by peternied** [comment]
authenticateRequest(...) checks hasValidSession() on every request which it authenticates.  It would be redundant for callers of that function also call hasValidSession

**Comment by nycodes9** [comment]
Any other way to check session before making making the login call ? (use case - I want to show a optional login page before getting the user to the webview for typing Microsoft credentials)

**Comment by peternied** [comment]
It sounds like you want to expose the loginSilent private function, I'd be happy to accept a pull request if you updated the interface and exposed the functionality your scenario needs.
