### ISSUE TITLE
Login Screen Hanges After pressing the Cancel button !

### ISSUE THREAD

**Issue by AnilSony** [microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter#7]
My name is Anil, My android app screen gets hangs after pressing the cancel button from the Login screen. I tested with different OS versions (KitKat, Lollipop & MarshMallow) it results the same. There is no way to escape from this screen, Device hardware button functionalities seems not working after this.Please Help.

Screenshots attached.
![sdk_loginscreen](https://cloud.githubusercontent.com/assets/4113314/25411376/316ca88a-29d1-11e7-9d35-182060e7a007.png)

**Comment by cbales** [comment]
Closing this issue. Please refer to [msa-auth-for-android/issues/32](https://github.com/OfficeDev/msa-auth-for-android/issues/32) for tracking. Thanks for reporting :)
